### ISSUE TITLE
Confusing behavior when empty lines are present

### ISSUE THREAD

**Issue by swrobel** [marudor/eslint-plugin-sort-imports-es6-autofix#3]
First of all, thanks for the plugin, I really needed this functionality. However, am I missing something, or is the grouping here rather arbitrary? It preserves the number of empty lines amongst my imports, but it moves imports above or below those blank lines in some cases, altering grouping of the imports.

Before:
```js
import { observer } from 'mobx-react';

import {
  Button,
  Card,
  CardHeader,
  CardBody,
  FormGroup,
  Input,
  Label,
  Table
} from 'reactstrap';
import {
  faShoppingCart,
  faMinusCircle
} from '@fortawesome/fontawesome-free-solid';
import FontAwesomeIcon from '@fortawesome/react-fontawesome';
import RowCol from 'shared/row_col';
import { StandardForm, StandardField } from 'shared/standard_field';
import { NextButton, PrevButton } from 'shared/form_buttons';

import cart from 'models/cart';
import users from 'models/user';
```
After:
```js
import {
  Button,
  Card,
  CardBody,
  CardHeader,
  FormGroup,
  Input,
  Label,
  Table
} from 'reactstrap';
import { NextButton, PrevButton } from 'shared/form_buttons';
import { StandardField, StandardForm } from 'shared/standard_field';

import {
  faMinusCircle,
  faShoppingCart
} from '@fortawesome/fontawesome-free-solid';
import { observer } from 'mobx-react';
import FontAwesomeIcon from '@fortawesome/react-fontawesome';
import PropTypes from 'prop-types';
import React from 'react';
import RowCol from 'shared/row_col';

import cart from 'models/cart';
import users from 'models/user';
```
Visual diff:
<img width="532" alt="screen shot 2018-01-22 at 10 07 42 am" src="https://user-images.githubusercontent.com/157270/35236419-1fc59860-ff5c-11e7-9301-042798c1571b.png">

**Comment by remhume** [comment]
Yes, this is because we only know where the import statements are and switch their positions.

I agree that this is sometimes weird and confusing (especially when there are comments above an import).

One option to fix this would be to sort all import statements behind the first one in the file it found.

Another option would be to only sort import statements within their blocks. Meaning when no newlines are inbetween.

We could also make this configurable although i think i'd like the second version better as default then because you quickly get how it works and you can use the behaviour to group imports in some files where it makes sense. thoughts? @marudor?

**Comment by swrobel** [comment]
I agree, sorting within groups (second version) would be my preference because we're trying to keep with a style for grouping (external first, then separate group for paths to our project code). Thanks for the quick response!

**Comment by remhume** [comment]
Alright i'll try to fix it right now :)

**Comment by hjylewis** [comment]
Any progress on this fix?

**Comment by remhume** [comment]
ya, sorry.
I had to refactor the code a lot (it was uite unreadable) and then my first draft of a fix didn't work out. it's not as easy as it sounds because you need to handle newlines with care and have to use regexes while the old code plainly switched all the import statements, which handled newlines automagically. we also had a few assumptions in the code based on switching all statements in the file (regarding the point in time when we apply fixes etc.)

After i didn't get it to work that evening i had my fulltime work and other stuff consumeing my time. I'll try to do it until next saturday but can't promise anything.

**Comment by hjylewis** [comment]
I'm taking a look too. I'd be interested in seeing the refactoring.

Something like:
```
const isLineBetween = previousDeclaration.loc.end.line < node.loc.start.line - 1;
```
Would tell us if the current node is separated for the previous declaration (by a newline or comment) in which case we could not report a rule violation. But since the fix functions sort all the statements at once, more work is required.

Is there a reason the fix functions switch all statements instead of just the specific out-of-order statement?

**Comment by swrobel** [comment]
@remhume would appreciate if you had time to review @hjylewis's PR. Would love to start using this plugin...
